---
  - name: Check whether {{ item.name }} schema has been imported
    shell: |
      ldapsearch -Z -x -D 'cn=Directory Manager' -w '{{ auth_ldap_admin_pwd_clear }}' -b cn=schema objectClasses | grep {{ item.checkattr }}
    register: check
    failed_when: False
    changed_when: False

  - name: Create ansible schema dir
    become: True
    file:
      path: /etc/ldap/ansible
      owner: root
      group: root
      mode: 0640
      state: directory

  - name: Upload {{ item.name }} schema
    become: True
    copy:
      src: "{{ item.file }}"
      dest: "/etc/ldap/ansible/{{ item.file }}"
      owner: root
      group: root
      mode: 0640

  - name: Import {{ item.name }} schema
    when: check.rc == 1
    become: True
    shell: "/usr/bin/ldapmodify -x -D 'cn=Directory Manager' -w '{{ auth_ldap_admin_pwd_clear }}' < /etc/ldap/ansible/{{ item.file }}"
