---
  - name: Create LDAP user
    run_once: true
    ldap_entry:
      dn: "uid={{ item.id }},ou=Users,{{ auth_ldap_domain_ldap }}"
      server_uri: "{{ auth_ldap_ansible_url }}"
      objectClass:
        - posixAccount
        - top
        - inetOrgPerson
      bind_dn: "cn=Directory Manager"
      bind_pw: "{{ auth_ldap_admin_pwd }}"
      state: present
      attributes:
        uid: "{{ item.id }}"
        uidNumber: "{{ item.uid }}"
        gidNumber: "{{ item.gid }}"
        homeDirectory: "/home/{{ item.id }}"
        sn: "{{ item.sn }}"
        givenName: "{{ item.givenName }}"
        mail: "{{ item.mail }}"
        cn: "{{ item.name }}"
    register: userchanged

  - name: Kerberize LDAP user
    run_once: true
    when: userchanged.changed
    become: True
    command: kadmin.local addprinc -randkey -x dn="uid={{ item.id }},ou=Users,{{ auth_ldap_domain_ldap }}" +requires_preauth -allow_svr "{{ item.id }}"
    tags:
      - skip_ansible_lint
