---
  - name: Create LDAP service user
    run_once: true
    ldap_entry:
      dn: "uid={{ item.host }},ou={{ item.service }},ou=TechnicalUsers,{{ auth_ldap_domain_ldap }}"
      server_uri: "{{ auth_ldap_ansible_url }}"
      objectClass:
        - top
        - inetOrgPerson
      bind_dn: "cn=Directory Manager"
      bind_pw: "{{ auth_ldap_admin_pwd_clear }}"
      state: present
      attributes:
        uid: "{{ item.host }}"
        cn: "{{ item.service }} on {{ item.host }}"
        sn: "Serviceaccount"
    register: userchanged

  - name: Kerberize LDAP user
    run_once: true
    when: userchanged.changed
    become: True
    command: kadmin.local addprinc -randkey -x dn="uid={{ item.host }},ou={{ item.service }},ou=TechnicalUsers,{{ auth_ldap_domain_ldap }}" +requires_preauth "{{ item.service }}/{{ item.host }}@{{ auth_ldap_domain|upper }}"

  - name: Export LDAP service user keytab
    when: (item.keytab is defined) and (ansible_fqdn == item.host)
    become: True
    command: "kadmin.local ktadd -k {{ item.keytab }} {{ item.service }}/{{ item.host }}@{{ auth_ldap_domain|upper }}"
    args:
      creates: "{{ item.keytab }}"

  - name: Set keytab permissions
    when: (item.keytab is defined) and (ansible_fqdn == item.host)
    become: True
    file:
      path: "{{ item.keytab }}"
      owner: "{{ item.ktowner }}"
      group: "{{ item.ktgroup }}"
      mode: "{{ item.ktmode }}"
